package vista;

import controlador.EstudianteController;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class LogIn extends javax.swing.JFrame {
    public static String user[] = new String[4];
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        btn_sesion.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_Usuario = new javax.swing.JTextField();
        jPF_Password = new javax.swing.JPasswordField();
        btn_sesion = new javax.swing.JButton();
        btn_registrarse = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jTF_Usuario.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jPanel1.add(jTF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 360, 30));
        jPanel1.add(jPF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 360, 30));

        btn_sesion.setBackground(new java.awt.Color(89, 47, 219));
        btn_sesion.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        btn_sesion.setText("Iniciar Sesión");
        btn_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sesionMouseEntered(evt);
            }
        });
        btn_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 180, -1));

        btn_registrarse.setBackground(new java.awt.Color(89, 47, 219));
        btn_registrarse.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        btn_registrarse.setText("Registrarse");
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 180, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sesion2.jpg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 192));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesionActionPerformed
        EstudianteController ec = new EstudianteController();
        String pass = new String(jPF_Password.getPassword());
        String usuario = jTF_Usuario.getText();
        btn_sesion.transferFocus();
        if(jTF_Usuario.getText().equals("") || pass.equals("")){
            JOptionPane.showMessageDialog(null, "No puede quedar campos vacios al iniciar sesion.");
        }else{           
            if(ec.existeUsuario(usuario)){
                String password = new String(jPF_Password.getPassword());
                String nom=ec.buscarNombre(usuario);
                if(ec.existePassword(usuario, password)){
                        user = ec.buscarDatosEstudiante(usuario);
                        Principal p = new Principal();
                        p.setVisible(true);
                        this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrecta.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrecta.");
            }
            
        }
    }//GEN-LAST:event_btn_sesionActionPerformed

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        Registrar r = new Registrar();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registrarseActionPerformed

    private void btn_sesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sesionMouseEntered
    
    }//GEN-LAST:event_btn_sesionMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JButton btn_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPF_Password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_Usuario;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
