/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.EstudianteController;
import controlador.MateriaController;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Principal extends javax.swing.JFrame {
    MateriaController mc = new MateriaController();
    LogIn li  = new LogIn();
    private int op=-1;
    private String nombre;
    private String codigo;
    private String usuario;
    private String password;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabel_nombre.setText(li.user[0]);
        jLabel_codigo.setText(li.user[1]);
        jTable_ListaMaterias.setModel(mc.mostrarListaMaterias(li.user[1]));
        btn_cancelar.setVisible(false);

    }
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Jpanel_cabecera = new javax.swing.JPanel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_nombre1 = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_nombre2 = new javax.swing.JLabel();
        jCB_Opciones = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_NombreMateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_Creditos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_Nota = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        btn_Conf_Editar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ListaMaterias = new javax.swing.JTable();
        btn_Eliminar = new javax.swing.JButton();
        btn_ponderado = new javax.swing.JButton();
        btn_MenuEditar = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(53, 0, 107));

        Jpanel_cabecera.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_nombre.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jLabel_nombre1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel_nombre1.setText("Nombre:     ");

        jLabel_codigo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N

        jLabel_nombre2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel_nombre2.setText(" Código:");

        jCB_Opciones.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jCB_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "Cambiar contraseña", "Salir" }));
        jCB_Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_OpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_cabeceraLayout = new javax.swing.GroupLayout(Jpanel_cabecera);
        Jpanel_cabecera.setLayout(Jpanel_cabeceraLayout);
        Jpanel_cabeceraLayout.setHorizontalGroup(
            Jpanel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_cabeceraLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Jpanel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_cabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel_nombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jpanel_cabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel_nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCB_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Jpanel_cabeceraLayout.setVerticalGroup(
            Jpanel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCB_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel2.setText("REGISTRAR MATERIA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel2.add(jTF_NombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 30));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setText("Creditos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(jTF_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 30));

        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setText("Nota");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel2.add(jTF_Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, 30));

        btn_registrar.setBackground(new java.awt.Color(0, 102, 0));
        btn_registrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("REGISTRAR");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, 40));

        btn_Conf_Editar.setBackground(new java.awt.Color(51, 153, 255));
        btn_Conf_Editar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btn_Conf_Editar.setText("Editar");
        btn_Conf_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Conf_EditarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Conf_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, 40));

        btn_cancelar.setBackground(new java.awt.Color(0, 102, 0));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 200, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setText("Materias");

        jTable_ListaMaterias.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jTable_ListaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_ListaMaterias.setColumnSelectionAllowed(true);
        jTable_ListaMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_ListaMaterias.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTable_ListaMaterias.setRowHeight(25);
        jScrollPane1.setViewportView(jTable_ListaMaterias);
        jTable_ListaMaterias.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btn_Eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Eliminar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_ponderado.setBackground(new java.awt.Color(0, 102, 0));
        btn_ponderado.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btn_ponderado.setForeground(new java.awt.Color(255, 255, 255));
        btn_ponderado.setText("Ver promedio");
        btn_ponderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ponderadoActionPerformed(evt);
            }
        });

        btn_MenuEditar.setBackground(new java.awt.Color(0, 51, 255));
        btn_MenuEditar.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        btn_MenuEditar.setForeground(new java.awt.Color(255, 255, 255));
        btn_MenuEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Editar nota", "Editar creditos" }));
        btn_MenuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_MenuEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btn_ponderado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ponderado)
                        .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_MenuEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jpanel_cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel_cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String nombre;
        float nota;
        int creditos;
        MateriaController mc = new MateriaController();
        if(jTF_NombreMateria.getText().equals("")||jTF_Nota.getText().equals("")||jTF_Creditos.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio.");
        }else{
            nombre = jTF_NombreMateria.getText();
            nota = new Float(jTF_Nota.getText());
            creditos = new Integer(jTF_Creditos.getText());
            codigo = jLabel_codigo.getText();
            if(mc.buscarMateriaPorCodigo(nombre, codigo)){
                JOptionPane.showMessageDialog(null, "Esta materia ya esta registrada.");
            }else{
                mc.insertar(creditos, nombre, nota, codigo);
                jTable_ListaMaterias.setModel(mc.mostrarListaMaterias(li.user[1]));
            }
        }
        jTF_NombreMateria.setText("");
        jTF_Creditos.setText("");
        jTF_Nota.setText("");
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_ponderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ponderadoActionPerformed
        float contCreditos=0;
        float contNota=0;
        float creditos;
        float nota;
        float prom;
        float totalMaterias = jTable_ListaMaterias.getRowCount();
        for(int i=0;i<totalMaterias;i++){
            nota = Float.parseFloat(jTable_ListaMaterias.getValueAt(i, 2).toString());
            contNota += nota;
        }
        if(totalMaterias>0){
            prom = contNota / totalMaterias;
            JOptionPane.showMessageDialog(null, "Su promedio es de "+prom);
        }else{
            JOptionPane.showMessageDialog(null, "No tiene materias registradaas, Su promedio es de 0");
        }
        
    }//GEN-LAST:event_btn_ponderadoActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        MateriaController mc = new MateriaController();
        String nombre = (String) jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(),0);
        if(!nombre.equals("")){
            mc.eliminar(nombre);
            jTable_ListaMaterias.setModel(mc.mostrarListaMaterias(li.user[1]));
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna materia a eliminar");
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_MenuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuEditarActionPerformed
        MateriaController mc = new MateriaController();
        String menuEditar = btn_MenuEditar.getSelectedItem().toString();
        if(menuEditar.equals("")||jTable_ListaMaterias.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna materia para editar");
        }else{
            switch(menuEditar){
                case "Editar nota":{
                    jTF_NombreMateria.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 0));
                    jTF_Creditos.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 1));
                    jTF_Nota.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 2));
                    btn_Conf_Editar.setVisible(true);
                    btn_registrar.setVisible(false);
                    jTF_NombreMateria.setEnabled(false);
                    jTF_Creditos.setEnabled(false);
                    jTF_Nota.setEnabled(true);
                    btn_cancelar.setVisible(true);
                    op=0;
                    break;
                }
                case "Editar creditos":{
                    jTF_NombreMateria.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 0));
                    jTF_Creditos.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 1));
                    jTF_Nota.setText((String)jTable_ListaMaterias.getValueAt(jTable_ListaMaterias.getSelectedRow(), 2));
                    btn_Conf_Editar.setVisible(true);
                    btn_registrar.setVisible(false);
                    jTF_NombreMateria.setEnabled(false);
                    jTF_Nota.setEnabled(false);
                    jTF_Creditos.setEnabled(true);
                    btn_cancelar.setVisible(true);
                    op=1;
                    break;
                }
            }
        }
    }//GEN-LAST:event_btn_MenuEditarActionPerformed

    private void btn_Conf_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Conf_EditarActionPerformed
        MateriaController mc = new MateriaController();
        switch(op){
            case 0:{
                nombre = jTF_NombreMateria.getText();
                int nota = new Integer(jTF_Nota.getText());
                mc.editarNota(nombre, nota);
                JOptionPane.showMessageDialog(null, "Nota editada exitosamente");
                jTF_NombreMateria.setText("");
                jTF_NombreMateria.setVisible(true);
                jTF_Creditos.setText("");
                jTF_Nota.setText("");
                btn_Conf_Editar.setVisible(false);
                btn_registrar.setVisible(true);
                jTF_NombreMateria.setEnabled(true);
                jTF_Creditos.setEnabled(true);
                jTable_ListaMaterias.setModel(mc.mostrarListaMaterias(jLabel_codigo.getText()));
                break;
            }
            case 1:{
                nombre = jTF_NombreMateria.getText();
                int creditos = new Integer(jTF_Creditos.getText());
                mc.editarCreditos(nombre, creditos);
                JOptionPane.showMessageDialog(null, "Creditos editados exitosamente");
                jTF_NombreMateria.setText("");
                jTF_NombreMateria.setVisible(true);
                jTF_Creditos.setText("");
                jTF_Nota.setText("");
                btn_Conf_Editar.setVisible(false);
                btn_registrar.setVisible(true);
                jTF_NombreMateria.setEnabled(true);
                jTF_Nota.setEnabled(true);
                jTable_ListaMaterias.setModel(mc.mostrarListaMaterias(jLabel_codigo.getText()));
                break;
            }
            default:{
                JOptionPane.showMessageDialog(null, "Elija una amateria para editar");
                break;
            }
        }
    }//GEN-LAST:event_btn_Conf_EditarActionPerformed

    private void jCB_OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_OpcionesActionPerformed
        String opcion = jCB_Opciones.getSelectedItem().toString();
        EstudianteController ec = new EstudianteController();
        LogIn li = new LogIn();
        String pass="";
        String usuario = li.user[2];
        switch(opcion){
            case "Cambiar contraseña":{
                pass = JOptionPane.showInputDialog(null, "Digite su contraseña actual");
                if(ec.existePassword(usuario, pass)){
                    CambiarPassword cp = new CambiarPassword();
                    cp.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "La contraseña es incorrecta");
                }
                break;
            }
            case "Salir":{
                li.setVisible(true);
                this.dispose();
                break;
            }
        }
    }//GEN-LAST:event_jCB_OpcionesActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        jTF_NombreMateria.setText("");
        jTF_Creditos.setText("");
        jTF_Nota.setText("");
        jTF_NombreMateria.setEnabled(true);
        jTF_Creditos.setEnabled(true);
        jTF_Nota.setEnabled(true);
        btn_cancelar.setVisible(false);
        btn_registrar.setVisible(true);
        btn_Conf_Editar.setVisible(false);
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_cabecera;
    private javax.swing.JButton btn_Conf_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JComboBox<String> btn_MenuEditar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_ponderado;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCB_Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_nombre1;
    private javax.swing.JLabel jLabel_nombre2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Creditos;
    private javax.swing.JTextField jTF_NombreMateria;
    private javax.swing.JTextField jTF_Nota;
    private javax.swing.JTable jTable_ListaMaterias;
    // End of variables declaration//GEN-END:variables
}
