-- MySQL Script generated by MySQL Workbench
-- Fri Aug  6 11:29:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ponderadoUnimag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ponderadoUnimag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ponderadoUnimag` DEFAULT CHARACTER SET utf8 ;
USE `ponderadoUnimag` ;

-- -----------------------------------------------------
-- Table `ponderadoUnimag`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponderadoUnimag`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Materiacol` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ponderadoUnimag`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponderadoUnimag`.`estudiante` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `materia_id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_estudiante_materia_idx` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_materia`
    FOREIGN KEY (`materia_id`)
    REFERENCES `ponderadoUnimag`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
