-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 22:19:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ponderadounimag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ponderadounimag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ponderadounimag` DEFAULT CHARACTER SET utf8 ;
USE `ponderadounimag` ;

-- -----------------------------------------------------
-- Table `ponderadounimag`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponderadounimag`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `creditos` INT NOT NULL,
  `nota` INT NOT NULL,
  `codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ponderadounimag`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ponderadounimag`.`estudiante` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
